const COLORS=['#dff5b2','#d9ebff','#ffe0d3','#eadcff','#d5f2e8','#fff0b9','#f7d8e7','#d8e4db'];
const CURRENCIES={KRW:{symbol:'₩',digits:0},JPY:{symbol:'¥',digits:0},USD:{symbol:'$',digits:2},EUR:{symbol:'€',digits:2},GBP:{symbol:'£',digits:2},CNY:{symbol:'¥',digits:2}};
const STORAGE_KEY='splittrip-manual-v1';
const state={people:[],receipts:[],activeReceipt:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,9),round=n=>Math.round((Number(n)||0)*100)/100;
const money=(n,c='KRW')=>{const d=CURRENCIES[c]?.digits??0;return(CURRENCIES[c]?.symbol||'')+(Number(n)||0).toLocaleString('ko-KR',{minimumFractionDigits:d,maximumFractionDigits:d})};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&Array.isArray(saved.people)&&Array.isArray(saved.receipts))Object.assign(state,saved)}catch(e){}}
function toast(msg){$('#toast p').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function initials(name){return name.trim().slice(0,1).toUpperCase()}

function renderPeople(){
  $('#peopleCount').textContent=state.people.length;
  $('#peopleList').innerHTML=state.people.length?state.people.map((p,i)=>`<div class="person-chip"><span class="avatar" style="background:${COLORS[i]}">${initials(p)}</span><b>${esc(p)}</b><button data-remove-person="${i}" aria-label="${esc(p)} 삭제">×</button></div>`).join(''):'<div class="people-empty"><span>＋</span><p><b>첫 참여자를 추가해 주세요</b><small>여행 멤버를 2명 이상 입력하세요.</small></p></div>';
  $$('[data-remove-person]').forEach(button=>button.onclick=()=>{if(state.receipts.length&&state.people.length<=2)return toast('정산 내역이 있을 때는 최소 2명이 필요해요.');const removed=+button.dataset.removePerson;state.people.splice(removed,1);state.receipts.forEach(r=>{if(r.payer===removed)r.payer=0;else if(r.payer>removed)r.payer--;r.items.forEach(x=>x.alloc=x.alloc.filter((_,i)=>i!==removed))});save();renderAll()});
}
function addPerson(){const input=$('#personInput'),name=input.value.trim();if(!name)return toast('이름을 입력해 주세요.');if(state.people.length>=8)return toast('참여자는 최대 8명까지 추가할 수 있어요.');if(state.people.includes(name))return toast('같은 이름이 이미 있어요.');state.people.push(name);state.receipts.forEach(r=>r.items.forEach(x=>x.alloc.push(0)));input.value='';save();renderAll()}
function blankItem(){return{id:uid(),name:'',qty:1,price:0,total:0,alloc:Array(state.people.length).fill(0)}}
function addReceipt(){if(state.people.length<2)return toast('참여자를 먼저 2명 이상 추가해 주세요.');state.receipts.push({id:uid(),name:`영수증 ${state.receipts.length+1}`,currency:'KRW',payer:0,items:[blankItem()]});state.activeReceipt=state.receipts.length-1;save();renderAll();$('#receiptEditor').scrollIntoView({behavior:'smooth',block:'center'})}
function deleteReceipt(){state.receipts.splice(state.activeReceipt,1);state.activeReceipt=Math.max(0,Math.min(state.activeReceipt,state.receipts.length-1));save();renderAll()}
function itemTotal(item){return round(Number.isFinite(item.total)?item.total:(item.qty||0)*(item.price||0))}
function receiptTotal(receipt){return round(receipt.items.reduce((sum,item)=>sum+itemTotal(item),0))}

function renderReceipts(){
  $('#receiptTabs').innerHTML=state.receipts.map((r,i)=>`<button class="receipt-tab ${i===state.activeReceipt?'active':''}" data-tab="${i}">영수증 ${i+1} · ${esc(r.name)}</button>`).join('');
  $$('[data-tab]').forEach(button=>button.onclick=()=>{state.activeReceipt=+button.dataset.tab;renderReceipts()});
  const r=state.receipts[state.activeReceipt];$('#manualEmpty').classList.toggle('hidden',!!r);if(!r){$('#receiptEditor').innerHTML='';return}
  r.items.forEach(item=>{item.qty=Math.max(1,+item.qty||1);item.price=round(item.price);item.total=round(Number.isFinite(item.total)?item.total:item.qty*item.price);while(item.alloc.length<state.people.length)item.alloc.push(0)});
  $('#receiptEditor').innerHTML=`<div class="editor"><div class="editor-meta"><div class="field"><label>영수증 이름</label><input data-meta="name" value="${esc(r.name)}"></div><div class="field"><label>통화</label><select data-meta="currency">${Object.keys(CURRENCIES).map(c=>`<option value="${c}" ${r.currency===c?'selected':''}>${CURRENCIES[c].symbol} ${c}</option>`).join('')}</select></div><div class="field"><label>결제한 사람</label><select data-meta="payer">${state.people.map((p,i)=>`<option value="${i}" ${r.payer===i?'selected':''}>${esc(p)}</option>`).join('')}</select></div><button class="delete-receipt" id="deleteReceiptBtn">영수증 삭제</button></div><div class="item-table-head"><span>품목</span><span>수량</span><span>개당 가격</span><span>품목 총액</span><span></span></div><div id="editorItems">${r.items.map((item,i)=>itemRow(item,i)).join('')}</div><div class="editor-footer"><button id="addItemBtn">＋ 품목 추가</button><span class="editor-total">영수증 합계 <b>${money(receiptTotal(r),r.currency)}</b></span></div></div>`;
  $$('[data-meta]').forEach(el=>el.onchange=()=>{r[el.dataset.meta]=el.dataset.meta==='payer'?+el.value:el.value;save();renderAll()});
  $$('[data-item-field]').forEach(el=>{el.oninput=()=>updateItem(r,+el.dataset.index,el.dataset.itemField,el.value,false);el.onchange=()=>updateItem(r,+el.dataset.index,el.dataset.itemField,el.value,true)});
  $$('[data-remove-item]').forEach(button=>button.onclick=()=>{r.items.splice(+button.dataset.removeItem,1);if(!r.items.length)r.items.push(blankItem());save();renderAll()});
  $('#addItemBtn').onclick=()=>{r.items.push(blankItem());save();renderAll()};$('#deleteReceiptBtn').onclick=deleteReceipt;
}
function itemRow(item,index){return`<div class="item-row"><input data-item-field="name" data-index="${index}" value="${esc(item.name)}" placeholder="품목명" aria-label="품목명"><input type="number" min="1" step="1" data-item-field="qty" data-index="${index}" value="${item.qty}" aria-label="수량"><input type="number" min="0" step="0.01" data-item-field="price" data-index="${index}" value="${item.price}" aria-label="개당 가격"><input type="number" min="0" step="0.01" data-item-field="total" data-index="${index}" value="${item.total}" aria-label="품목 총액"><button data-remove-item="${index}" aria-label="품목 삭제">×</button></div>`}
function updateItem(r,index,field,value,redraw=true){const item=r.items[index];if(field==='name')item.name=value.trim();if(field==='qty'){item.qty=Math.max(1,Math.floor(+value||1));item.price=item.total>0?round(item.total/item.qty):round(item.price);item.total=round(item.qty*item.price);item.alloc=item.alloc.map(v=>Math.min(v,item.qty))}if(field==='price'){item.price=Math.max(0,round(value));item.total=round(item.qty*item.price)}if(field==='total'){item.total=Math.max(0,round(value));item.price=round(item.total/item.qty)}save();if(redraw)return renderAll();const priceInput=$(`[data-item-field="price"][data-index="${index}"]`),totalInput=$(`[data-item-field="total"][data-index="${index}"]`),qtyInput=$(`[data-item-field="qty"][data-index="${index}"]`);if(priceInput)priceInput.value=item.price;if(totalInput)totalInput.value=item.total;if(qtyInput)qtyInput.value=item.qty;const totalLabel=$('.editor-total b');if(totalLabel)totalLabel.textContent=money(receiptTotal(r),r.currency);renderAllocation();updateSummary()}

function renderAllocation(){
  const cards=[];state.receipts.forEach((r,ri)=>r.items.forEach((item,ii)=>{while(item.alloc.length<state.people.length)item.alloc.push(0);const used=item.alloc.reduce((a,b)=>a+b,0),done=used===item.qty;cards.push(`<div class="alloc-card ${done?'complete':''}"><div class="alloc-top"><span class="alloc-icon">${['🍜','☕','🍺','🥟','🛍️'][(ri+ii)%5]}</span><div class="alloc-name"><b>${esc(item.name||'이름 없는 품목')}</b><small>영수증 ${ri+1} · ${money(item.price,r.currency)} × ${item.qty}개 = ${money(itemTotal(item),r.currency)}</small></div><span class="alloc-state">${done?'✓ 배분 완료':`${used} / ${item.qty}개`}</span></div><div class="alloc-controls">${state.people.map((p,pi)=>`<div class="person-qty"><span class="mini-avatar" style="background:${COLORS[pi]}">${initials(p)}</span><span>${esc(p)}</span><div class="qty-control"><button data-qty="-1" data-r="${ri}" data-i="${ii}" data-p="${pi}">−</button><span>${item.alloc[pi]||0}</span><button data-qty="1" data-r="${ri}" data-i="${ii}" data-p="${pi}">＋</button></div></div>`).join('')}</div></div>`)}));
  $('#allocationList').innerHTML=cards.join('');$$('[data-qty]').forEach(button=>button.onclick=()=>changeQty(+button.dataset.r,+button.dataset.i,+button.dataset.p,+button.dataset.qty));const has=state.receipts.length>0;$('#allocation').classList.toggle('hidden-section',!has);$('#result').classList.toggle('hidden-section',!has);
}
function changeQty(ri,ii,pi,delta){const item=state.receipts[ri].items[ii],used=item.alloc.reduce((a,b)=>a+b,0),next=(item.alloc[pi]||0)+delta;if(next<0)return;if(delta>0&&used>=item.qty)return toast(`“${item.name||'품목'}”은(는) ${item.qty}개까지만 배분할 수 있어요.`);item.alloc[pi]=next;save();renderAllocation();updateSummary()}
function calculate(){if(state.people.length<2)return toast('참여자를 먼저 2명 이상 추가해 주세요.');if(!state.receipts.length)return toast('먼저 영수증을 추가해 주세요.');const invalidInput=state.receipts.flatMap(r=>r.items).find(item=>!item.name.trim()||item.qty<1||item.price<=0);if(invalidInput)return toast('모든 품목의 이름·수량·금액을 입력해 주세요.');const invalid=state.receipts.flatMap(r=>r.items.map(item=>({name:item.name,ok:item.alloc.reduce((a,b)=>a+b,0)===item.qty}))).filter(x=>!x.ok);if(invalid.length){$('#modalText').textContent=`${invalid.slice(0,3).map(x=>'“'+x.name+'”').join(', ')}${invalid.length>3?' 외 '+(invalid.length-3)+'개':''} 품목의 수량을 확인해 주세요.`;$('#modal').classList.remove('hidden');return}renderResults();$('#result').classList.remove('hidden-section');$$('.step').forEach((x,i)=>x.classList.toggle('active',i===3));$('#result').scrollIntoView({behavior:'smooth'})}
function renderResults(){
  const html=[];state.people.forEach((person,pi)=>{const outgoing={},incoming={};state.receipts.forEach(r=>r.items.forEach(item=>state.people.forEach((_,consumer)=>{const amount=(item.alloc[consumer]||0)*item.price;if(!amount||consumer===r.payer)return;if(consumer===pi){const key=`${r.payer}|${r.currency}`;outgoing[key]=(outgoing[key]||0)+amount}if(r.payer===pi){const key=`${consumer}|${r.currency}`;incoming[key]=(incoming[key]||0)+amount}})));const outs=Object.entries(outgoing),ins=Object.entries(incoming),payer=ins.length>0;const headline=outs.length?Object.entries(outs.reduce((a,[k,n])=>{const c=k.split('|')[1];a[c]=(a[c]||0)+n;return a},{})).map(([c,n])=>money(n,c)).join(' + '):payer?'받을 금액 있음':money(0,'KRW');const detail=[...outs.map(([k,n])=>`${state.people[+k.split('|')[0]]}에게 ${money(n,k.split('|')[1])}`),...ins.map(([k,n])=>`${state.people[+k.split('|')[0]]}에게 받을 금액 ${money(n,k.split('|')[1])}`)].join('<br>')||'추가 송금 내역이 없어요.';html.push(`<div class="result-card ${payer&&!outs.length?'payer':''}"><div class="result-person"><span class="avatar" style="background:${COLORS[pi]};color:#17231f">${initials(person)}</span><b>${esc(person)}</b></div><small>${outs.length?'총 보낼 금액':payer?'결제자 정산':'정산 금액'}</small><strong>${headline}</strong><p>${detail}</p></div>`)});$('#resultCards').innerHTML=html.join('');updateSummary();
}
function updateSummary(){const all=state.receipts.flatMap(r=>r.items),done=all.filter(x=>x.alloc.reduce((a,b)=>a+b,0)===x.qty).length;$('#receiptCount').textContent=state.receipts.length+'장';const totals={};state.receipts.forEach(r=>totals[r.currency]=(totals[r.currency]||0)+receiptTotal(r));$('#grandTotal').textContent=Object.entries(totals).map(([c,n])=>money(n,c)).join(' + ')||'—';$('#doneItems').textContent=`${done} / ${all.length}`;$('#actionHint').textContent=state.people.length<2?`참여자를 ${2-state.people.length}명 더 추가해 주세요`:state.receipts.length?`${all.length}개 품목 중 ${done}개 배분 완료`:'영수증을 추가해 정산을 시작하세요'}
function renderAll(){renderPeople();renderReceipts();renderAllocation();updateSummary();$('#addReceiptBtn').disabled=state.people.length<2;$$('.step').forEach((step,i)=>step.classList.toggle('active',i===(state.receipts.length?2:0)))}

$('#addPersonBtn').onclick=addPerson;$('#personInput').onkeydown=e=>{if(e.key==='Enter')addPerson()};$('#addReceiptBtn').onclick=addReceipt;$('#calculateBtn').onclick=calculate;
$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};
$$('.step').forEach(step=>step.onclick=()=>$('#'+step.dataset.target).scrollIntoView({behavior:'smooth',block:'start'}));
$('#resetBtn').onclick=()=>{if(confirm('현재 정산 내용을 모두 지울까요?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
load();renderAll();
